kind: Service
apiVersion: v1
metadata:
  name: airflow-flower
  namespace: ersin-poc
spec:
  ports:
    - name: 5555-tcp
      protocol: TCP
      port: 5555
      targetPort: 5555
  selector:
    deployment: airflow-flower
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack 